backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files: 
      - label: "Home Page"
        name: 'home'
        file: 'assets/content/home.json'
        editor:
          preview: false
        fields:
          - label: "Banner Image"
            name: "banner_image"
            widget: "image"
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Intro Video, name: intro_video, widget: string}
  - label: "Tour"
    name: "tour"
    folder: "assets/content/tours"
    create: true
    slug: '{{slug}}'
    format: 'json'
    editor:
      preview: false
    fields:
      - label: "Date" 
        name: "date" 
        widget: datetime
        default: ""
        format: "LLL"
      - {label: Venue, name: venue, widget: string }
      - {label: Location, name: Location, widget: string }
      - {label: Link, name: link, widget: string }
  - label: "Album"
    name: "album"
    folder: "assets/content/albums"
    create: true
    slug: '{{slug}}'
    format: 'json'
    editor:
      preview: false
    fields:
      - {label: Album Name, name: name, widget: string }
      - {label: Album Author, name: author, widget: string }
      - {label: Link, name: link, widget: string }
  - label: "Social Media Link"
    name: "social_link"
    folder: "assets/content/social-links"
    create: true
    format: 'json'
    editor:
      preview: false
    fields: 
      - label: "Name"
        name: "name"
        widget: "select"
        options: ["facebook", "instagram", "youtube", "spotify"]
      - {label: Link, name: link, widget: string }



