backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files: 
      - label: "Home Page"
        name: 'home'
        file: 'assets/content/home.json'
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: Intro Video, name: intro_video, widget: string}